baseURL: http://www.victoria-julio.com/
languageCode: en-us
title: Moldova 2020
theme: hugo-fresh
googleAnalytics: #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warnings
disableKinds:
 -taxonomy
 -taxonomyTerm


params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy 
  description: 
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/fresh.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: We're getting married. Technically, for the second time.
    # Hero subtitle (optional)
    subtitle: Join us as we make it official in Chisinau on September 12, 2020.
    # Button text
    buttontext: RSVP
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: photos/hero.jfif
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Features
    url: /
  - title: Pricing
    url: /
  - title: Dropdown
    sublinks:
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
    - title: Dropdown item
      url: /
  - title: RSVP
    url: /
    button: true
  section1:
    title: Helpful guides
    subtitle: to get you started
    tiles:
    - title: How to get there
      icon: mouse-globe
      text: Our tips to get tickets to and from Chisinau
      url: /
      buttonText: Take me there
    - title: Where to stay
      icon: laptop-cloud
      text: Our hotel recommendations and how to reach them
      url: /
      buttonText: Take me there
    - title: Plan a Euro-tour
      icon: plug-cloud
      text: Here are our suggestions for cool destinations to visit
      url: /
      buttonText: Take me there
  section2:
    title: So this is how it's gonna go down
    subtitle: Schedule of festivities
    features:
    - title: Pre-wedding get together
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Wedding at the church
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: After-wedding "let's be hang over together"
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: Join us!
    subtitle: We'd love to see you there
    image: illustrations/mockups/app-mockup.png
    buttonText: RSVP
    buttonLink: "#"
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Social media
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/
      icon: twitter
    - link: https://instagram.com
      icon: instagram
    bulmalogo: false
    quicklinks:
      column1:
        title: ""
      column2:
        title: ""
      column3:
        title: ""